openapi: 3.0.3
info:
  title: BerlinClock API
  description: API for calculating Berlin Clock time.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api

paths:
  /berlinclock:
    post:
      operationId: calculateBerlinClockTime
      requestBody:
        required: true
        description: Time values to be converted to Berlin Clock format.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BerlinClockRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerlinClockResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TimeComponent:
      type: object
      required:
        - hours
        - minutes
        - seconds
      properties:
        hours:
          type: string
        minutes:
          type: string
        seconds:
          type: string
    BerlinClockResponse:
      type: object
      required:
        - digitalTime
        - detailedBerlinTime
        - berlinTime
      properties:
        digitalTime:
          type: string
        detailedBerlinTime:
          $ref: '#/components/schemas/DetailedBerlinTime'
        berlinTime:
          type: string
    DetailedBerlinTime:
      type: object
      properties:
        secondsLamp:
          type: string
        topFiveHourLamps:
          type: string
        bottomOneHourLamps:
          type: string
        topFiveMinuteLamps:
          type: string
        bottomOneMinuteLamps:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
        detailedErrorMessage:
          type: string
    BerlinClockRequest:
      type: object
      properties:
        time:
          $ref: '#/components/schemas/TimeComponent'
